from app.models.product import Product
from app.db.database import SessionLocal

data = [
    {
        "name": "iPhone 16",
        "slug": "iphone-16",
        "description": "Latest flagship smartphone with A18 chip.",
        "price": 1199.99,
        "stock_quantity": 20,
        "sku": "SKU-P-001",
        "image_url": "https://example.com/p1.jpg",
        "category_id": 1,
        "is_active": True,
    },
    {
        "name": "Samsung Galaxy S25",
        "slug": "samsung-galaxy-s25",
        "description": "High-end Android smartphone with advanced camera.",
        "price": 1099.00,
        "stock_quantity": 30,
        "sku": "SKU-P-002",
        "image_url": "https://example.com/p2.jpg",
        "category_id": 1,
        "is_active": True,
    },
    {
        "name": "Google Pixel 10",
        "slug": "google-pixel-10",
        "description": "Google’s pure Android experience with AI camera.",
        "price": 899.00,
        "stock_quantity": 15,
        "sku": "SKU-P-003",
        "image_url": "https://example.com/p3.jpg",
        "category_id": 1,
        "is_active": True,
    },
    {
        "name": "MacBook Pro M3 Max",
        "slug": "macbook-pro-m3-max",
        "description": "Professional laptop for developers and creators.",
        "price": 3499.00,
        "stock_quantity": 8,
        "sku": "SKU-L-001",
        "image_url": "https://example.com/l1.jpg",
        "category_id": 2,
        "is_active": True,
    },
    {
        "name": "Dell XPS 15",
        "slug": "dell-xps-15",
        "description": "Premium Windows ultrabook.",
        "price": 1999.99,
        "stock_quantity": 12,
        "sku": "SKU-L-002",
        "image_url": "https://example.com/l2.jpg",
        "category_id": 2,
        "is_active": True,
    },
    {
        "name": "Lenovo ThinkPad X1 Carbon",
        "slug": "thinkpad-x1-carbon",
        "description": "Business laptop with robust build.",
        "price": 1799.00,
        "stock_quantity": 20,
        "sku": "SKU-L-003",
        "image_url": "https://example.com/l3.jpg",
        "category_id": 2,
        "is_active": True,
    },
    {
        "name": "AirPods Pro 3",
        "slug": "airpods-pro-3",
        "description": "Noise-cancelling wireless earbuds.",
        "price": 299.00,
        "stock_quantity": 60,
        "sku": "SKU-A-001",
        "image_url": "https://example.com/a1.jpg",
        "category_id": 3,
        "is_active": True,
    },
    {
        "name": "Sony WH-1000XM6",
        "slug": "sony-wh-1000xm6",
        "description": "Industry-leading ANC headphones.",
        "price": 399.00,
        "stock_quantity": 45,
        "sku": "SKU-A-002",
        "image_url": "https://example.com/a2.jpg",
        "category_id": 3,
        "is_active": True,
    },
    {
        "name": "JBL Tune 710BT",
        "slug": "jbl-tune-710bt",
        "description": "Affordable wireless headphones.",
        "price": 79.99,
        "stock_quantity": 100,
        "sku": "SKU-A-003",
        "image_url": "https://example.com/a3.jpg",
        "category_id": 3,
        "is_active": True,
    },
    {
        "name": "Apple Watch Series 10",
        "slug": "apple-watch-series-10",
        "description": "Latest smartwatch with fitness tracking.",
        "price": 499.00,
        "stock_quantity": 50,
        "sku": "SKU-W-001",
        "image_url": "https://example.com/w1.jpg",
        "category_id": 4,
        "is_active": True,
    },
    {
        "name": "Samsung Galaxy Watch 7",
        "slug": "galaxy-watch-7",
        "description": "Premium Android smartwatch.",
        "price": 349.00,
        "stock_quantity": 25,
        "sku": "SKU-W-002",
        "image_url": "https://example.com/w2.jpg",
        "category_id": 4,
        "is_active": True,
    },
    {
        "name": "Fitbit Charge 7",
        "slug": "fitbit-charge-7",
        "description": "Fitness tracker with long battery life.",
        "price": 129.00,
        "stock_quantity": 90,
        "sku": "SKU-W-003",
        "image_url": "https://example.com/w3.jpg",
        "category_id": 4,
        "is_active": True,
    },
    {
        "name": "Logitech MX Master 4",
        "slug": "mx-master-4",
        "description": "Premium productivity mouse.",
        "price": 119.00,
        "stock_quantity": 70,
        "sku": "SKU-PC-001",
        "image_url": "https://example.com/pc1.jpg",
        "category_id": 5,
        "is_active": True,
    },
    {
        "name": "Razer Huntsman V3",
        "slug": "razer-huntsman-v3",
        "description": "Gaming mechanical keyboard.",
        "price": 199.00,
        "stock_quantity": 35,
        "sku": "SKU-PC-002",
        "image_url": "https://example.com/pc2.jpg",
        "category_id": 5,
        "is_active": True,
    },
    {
        "name": "Logitech C920 HD Pro",
        "slug": "logitech-c920-hd",
        "description": "1080p webcam for meetings and streaming.",
        "price": 69.99,
        "stock_quantity": 40,
        "sku": "SKU-PC-003",
        "image_url": "https://example.com/pc3.jpg",
        "category_id": 5,
        "is_active": True,
    },
    {
        "name": "Anker 20,000mAh Power Bank",
        "slug": "anker-20000mah-powerbank",
        "description": "Fast-charging portable power bank.",
        "price": 39.99,
        "stock_quantity": 150,
        "sku": "SKU-AC-001",
        "image_url": "https://example.com/ac1.jpg",
        "category_id": 6,
        "is_active": True,
    },
    {
        "name": "Apple 35W Dual USB-C Charger",
        "slug": "apple-35w-dual-charger",
        "description": "Premium dual-port charging brick.",
        "price": 59.00,
        "stock_quantity": 85,
        "sku": "SKU-AC-002",
        "image_url": "https://example.com/ac2.jpg",
        "category_id": 6,
        "is_active": True,
    },
    {
        "name": "Belkin 3-in-1 MagSafe Stand",
        "slug": "belkin-magsafe-stand",
        "description": "Wireless charging dock for Apple devices.",
        "price": 149.00,
        "stock_quantity": 25,
        "sku": "SKU-AC-003",
        "image_url": "https://example.com/ac3.jpg",
        "category_id": 6,
        "is_active": True,
    },
    {
        "name": "SanDisk 128GB USB 3.0 Flash Drive",
        "slug": "sandisk-128gb-usb",
        "description": "Fast and portable USB storage.",
        "price": 17.99,
        "stock_quantity": 200,
        "sku": "SKU-ST-001",
        "image_url": "https://example.com/st1.jpg",
        "category_id": 7,
        "is_active": True,
    },
    {
        "name": "Samsung T7 1TB SSD",
        "slug": "samsung-t7-1tb",
        "description": "Ultra-fast portable SSD.",
        "price": 129.99,
        "stock_quantity": 40,
        "sku": "SKU-ST-002",
        "image_url": "https://example.com/st2.jpg",
        "category_id": 7,
        "is_active": True,
    },
    {
        "name": "Seagate 4TB External HDD",
        "slug": "seagate-4tb-hdd",
        "description": "High-capacity external hard drive.",
        "price": 89.99,
        "stock_quantity": 35,
        "sku": "SKU-ST-003",
        "image_url": "https://example.com/st3.jpg",
        "category_id": 7,
        "is_active": True,
    },
    {
        "name": "Echo Dot 6th Gen",
        "slug": "echo-dot-6",
        "description": "Smart home assistant speaker.",
        "price": 49.99,
        "stock_quantity": 120,
        "sku": "SKU-SM-001",
        "image_url": "https://example.com/sm1.jpg",
        "category_id": 8,
        "is_active": True,
    },
    {
        "name": "Google Nest Hub 3",
        "slug": "google-nest-hub-3",
        "description": "Smart home screen with assistant.",
        "price": 129.00,
        "**stock_quantity**": 50,
        "sku": "SKU-SM-002",
        "image_url": "https://example.com/sm2.jpg",
        "category_id": 8,
        "is_active": True,
    },
    {
        "name": "Philips Hue Smart Bulb",
        "slug": "philips-new-hue-bulb",
        "description": "Smart LED bulb with millions of colors.",
        "price": 29.99,
        "stock_quantity": 200,
        "sku": "SKU-SMP-003",
        "image_url": "https://example.com/sm3.jpg",
        "category_id": 8,
        "is_active": True,
    },
]


def seed_product():
    db = SessionLocal()
    db.query(Product).delete()
    db.commit()

    db.bulk_insert_mappings(Product, data)
    db.commit()
